## Error

### Case 1: unpack_user_and_item=True

```
---- Funk Matrix Factorization ----
{'timestamp': 874731910000000000, 'title': "My Best Friend's Wedding (1997)", 'release_date': 866764800000000000, 'genres': 'comedy, romance', 'age': 21.0, 'gender': 'M', 'occupation': 'student', 'zip_code': '48823'} {'user': '259', 'item': '255'}
Traceback (most recent call last):
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 415, in <module>
    main()
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 403, in main
    funk_mf(True)
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 89, in funk_mf
    evaluate(model, True)
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 19, in evaluate
    _ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 341, in progressive_val_score
    for checkpoint in checkpoints:
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 167, in iter_progressive_val_score
    yield from _progressive_validation(
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 47, in _progressive_validation
    preds[i] = pred_func(x=x, **kwargs)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/preprocessing/pred_clipper.py", line 61, in predict_one
    y_pred = self.regressor.predict_one(x, **kwargs)
TypeError: predict_one() got multiple values for argument 'user'
```


```
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/preprocessing/pred_clipper.py", line 61, in predict_one
    y_pred = self.regressor.predict_one(x, **kwargs)
TypeError: predict_one() got multiple values for argument 'user'
```

File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/preprocessing/pred_clipper.py", line 61, in predict_one:
```python
    def predict_one(self, x, **kwargs):
        print(x, kwargs)
        y_pred = self.regressor.predict_one(x, **kwargs)
        return utils.math.clamp(y_pred, self.y_min, self.y_max)
```

At this point, the prited output is
```
{'timestamp': 874731910000000000, 'title': "My Best Friend's Wedding (1997)", 'release_date': 866764800000000000, 'genres': 'comedy, romance', 'age': 21.0, 'gender': 'M', 'occupation': 'student', 'zip_code': '48823'} {'user': '259', 'item': '255'}
```

1. `x`: `{'timestamp': 874731910000000000, 'title': "My Best Friend's Wedding (1997)", 'release_date': 866764800000000000, 'genres': 'comedy, romance', 'age': 21.0, 'gender': 'M', 'occupation': 'student', 'zip_code': '48823'}`
1. `kwargs`: `{'user': '259', 'item': '255'}`

Next point is that `regressor.predict_one` means `reco.FunkMF(**funk_mf_params).predict_one`.

```python
    def predict_one(self, user, item, x=None):
        return np.dot(self.u_latents[user], self.i_latents[item])
```

This function was changed in https://github.com/online-ml/river/pull/832/files

the first argument should be `user`, and the second argument should be `item`.

Reproduced the error:

```python
def predict_one(user, item, x=None):
    print(f"{user=}, {item=}, {x=}")

print(*{'user': '259', 'item': '255'})
predict_one({'timestamp': 874731910000000000, 'title': "My Best Friend's Wedding (1997)", 'release_date': 866764800000000000, 'genres': 'comedy, romance', 'age': 21.0, 'gender': 'M', 'occupation': 'student', 'zip_code': '48823'}, **{'user': '259', 'item': '255'})
```

```
user item
Traceback (most recent call last):
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/check.py", line 5, in <module>
    predict_one({'timestamp': 874731910000000000, 'title': "My Best Friend's Wedding (1997)", 'release_date': 866764800000000000, 'genres': 'comedy, romance', 'age': 21.0, 'gender': 'M', 'occupation': 'student', 'zip_code': '48823'}, **{'user': '259', 'item': '255'})
TypeError: predict_one() got multiple values for argument 'user'
```

The ****kwargs** will give you all keyword arguments except for those corresponding to a formal parameter as a dictionary.

Because x has the keyword `user` while positional argument also has `user`, we got the error `predict_one() got multiple values for argument 'user'`.

### Case 2: unpack_user_and_item=False

```
{'user': '259', 'item': '255', 'timestamp': 874731910000000000, 'title': "My Best Friend's Wedding (1997)", 'release_date': 866764800000000000, 'genres': 'comedy, romance', 'age': 21.0, 'gender': 'M', 'occupation': 'student', 'zip_code': '48823'} {}
Traceback (most recent call last):
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 415, in <module>
    main()
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 403, in main
    funk_mf(True)
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 89, in funk_mf
    evaluate(model, False)
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/main.py", line 19, in evaluate
    _ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 341, in progressive_val_score
    for checkpoint in checkpoints:
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 167, in iter_progressive_val_score
    yield from _progressive_validation(
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 47, in _progressive_validation
    preds[i] = pred_func(x=x, **kwargs)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/preprocessing/pred_clipper.py", line 61, in predict_one
    y_pred = self.regressor.predict_one(x, **kwargs)
TypeError: predict_one() missing 1 required positional argument: 'item'
```

```
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/preprocessing/pred_clipper.py", line 61, in predict_one
    y_pred = self.regressor.predict_one(x, **kwargs)
TypeError: predict_one() missing 1 required positional argument: 'item'
```

1. `x`: `{'user': '259', 'item': '255', 'timestamp': 874731910000000000, 'title': "My Best Friend's Wedding (1997)", 'release_date': 866764800000000000, 'genres': 'comedy, romance', 'age': 21.0, 'gender': 'M', 'occupation': 'student', 'zip_code': '48823'}`
1. `kwargs`: `{}`

## Issues

<!--
Before submitting a bug, please make sure the issue hasn't been already
addressed by searching through the past issues.
-->
## Versions
<!--
Describe all the versions that can help us to correct the bug
-->

**river version**: 0.13.0
**Python version**: 3.9.4
**Operating system**: MacBook Pro (13-inch, M1, 2020)

## Describe the bug
<!--
A clear and concise description of the bug.
-->
Examples in [MF for recommender system](https://riverml.xyz/0.13.0/examples/matrix-factorization-for-recommender-systems/part-1/#funk-matrix-factorization-funkmf) fail. e.g. FunkMF with PredClipper

## Steps/code to reproduce

### 1. unpack_user_and_item=True

```python
from river import datasets, metrics, optim, preprocessing, reco
from river.evaluate import progressive_val_score


def evaluate(model, unpack_user_and_item=True):
    X_y = datasets.MovieLens100K(unpack_user_and_item)
    metric = metrics.MAE() + metrics.RMSE()
    _ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)


funk_mf_params = {
    'n_factors': 10,
    'optimizer': optim.SGD(0.05),
    'l2': 0.1,
    'initializer': optim.initializers.Normal(mu=0., sigma=0.1, seed=73)
}

model = preprocessing.PredClipper(
    regressor=reco.FunkMF(**funk_mf_params),
    y_min=1,
    y_max=5
)

evaluate(model)
```

Result:
```
Traceback (most recent call last):
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/report.py", line 24, in <module>
    evaluate(model)
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/report.py", line 8, in evaluate
    _ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 341, in progressive_val_score
    for checkpoint in checkpoints:
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 167, in iter_progressive_val_score
    yield from _progressive_validation(
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 47, in _progressive_validation
    preds[i] = pred_func(x=x, **kwargs)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/preprocessing/pred_clipper.py", line 60, in predict_one
    y_pred = self.regressor.predict_one(x, **kwargs)
TypeError: predict_one() got multiple values for argument 'user'
```

### 1. unpack_user_and_item=False

```python
from river import datasets, metrics, optim, preprocessing, reco
from river.evaluate import progressive_val_score


def evaluate(model, unpack_user_and_item=True):
    X_y = datasets.MovieLens100K(unpack_user_and_item)
    metric = metrics.MAE() + metrics.RMSE()
    _ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)


funk_mf_params = {
    'n_factors': 10,
    'optimizer': optim.SGD(0.05),
    'l2': 0.1,
    'initializer': optim.initializers.Normal(mu=0., sigma=0.1, seed=73)
}

model = preprocessing.PredClipper(
    regressor=reco.FunkMF(**funk_mf_params),
    y_min=1,
    y_max=5
)

evaluate(model, False)
```

Result:

```
Traceback (most recent call last):
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/report.py", line 24, in <module>
    evaluate(model, False)
  File "/Users/m.naka/repos/nakamasato/ml-training/river/examples/fm-for-datalens/report.py", line 8, in evaluate
    _ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 341, in progressive_val_score
    for checkpoint in checkpoints:
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 167, in iter_progressive_val_score
    yield from _progressive_validation(
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/evaluate/progressive_validation.py", line 47, in _progressive_validation
    preds[i] = pred_func(x=x, **kwargs)
  File "/Users/m.naka/repos/nakamasato/ml-training/venv/lib/python3.9/site-packages/river/preprocessing/pred_clipper.py", line 60, in predict_one
    y_pred = self.regressor.predict_one(x, **kwargs)
TypeError: predict_one() missing 1 required positional argument: 'item'
````
## Rough Investigation

This error is related to https://github.com/online-ml/river/pull/832

1. regressor.predict_one:
    https://github.com/online-ml/river/blob/6805de7baf998212fb4aa05f99d8b20626f66a51/river/reco/funk_mf.py#L128-L129
1. pred_clipper.predict_one
    https://github.com/online-ml/river/blob/441cc5cfdc3a8bc82faabe15e74a818c3cd65ece/river/preprocessing/pred_clipper.py#L59-L61
1. unpack_user_and_item=True:
    `{'user': '259', 'item': '255'}` is passed to the `**kwargs`, which conflicts with the positional argument `user`
1. unpack_user_and_item=False:
    The second positional argument `item` is missed as `{full dataset}` and `{}` are passed to `regressor.predict_one` in PredClipper

-> Found somehow

`y_pred = self.regressor.predict_one(x=x, **kwargs)`

```python
    def predict_one(self, x, **kwargs):
        print(x, kwargs)
        y_pred = self.regressor.predict_one(x=x, **kwargs)
        return utils.math.clamp(y_pred, self.y_min, self.y_max)
```
